### ISSUE TITLE
To add a cloud a storage for photos 

### ISSUE THREAD

**Issue by danielmarv** [danielmarv/ChatRoom#2]
The current storage for our photos is hectic so we should look for the way to use cloud storage like Cloudinary which will help us to run our back (server ) smoothly

**Comment by danielmarv** [comment]
@Amnish04 could you help me about this issue if you don't mind

**Comment by Amnish04** [comment]
@danielmarv I think this is an interesting task, would love to try it out.

But I had a question. When I tried your application, I couldn't login or register myself, hence always stuck on the auth screen. Is that a bug or the area still needs to be implemented?
The problem is without being able to login, I won't be able to look much into the issue.

**Edit:** Its working now, starting to take a look.

**Comment by danielmarv** [comment]
did it work for you

**Comment by danielmarv** [comment]
if you don't mind can i get your contact information
i am Daniel
mail: danientege785@gmail.com
WhatsApp: +256785046375

**Comment by danielmarv** [comment]
![chatroom3](https://github.com/danielmarv/ChatRoom/assets/103020028/96002122-b684-44b5-af09-974f1ec01c3e)
![chatroom1](https://github.com/danielmarv/ChatRoom/assets/103020028/faea3466-1eee-4695-9613-bd59db1586e9)
![chatroom2](https://github.com/danielmarv/ChatRoom/assets/103020028/ff360aa8-9244-412a-a487-2f4e0ee67549)

**Comment by Amnish04** [comment]
@danielmarv Hi Daniel, sorry I got a little busy with school projects. I tried to reach out to you on Whatsapp, but seems like your number is not registered with it.

I am starting to look into this issue again. Will need your assistance

**Comment by danielmarv** [comment]
+256785046375 that's my what's app number

**Comment by danielmarv** [comment]
ok what your number

**Comment by Amnish04** [comment]
> ok what your number

Just sent you a text.
